// snapsitebug.jsx
// Renders a 'generated by...' DIV tag

const React = require('react');

var SnapBug = React.createClass({
    displayName: "HolisticPoweredByFooter",

    getInitialState: function() {
        return ({ expanded: false });
    },

    onToggleBuildInfo: function() {
        var state = this.state;
        this.setState({ expanded: !state.expanded });
    },

    render: function() {
        try {
            const metadata = this.props.document.metadata;
            const theme = metadata.site.theme;
            const agent = metadata.agent;
            const session = metadata.session;


            if (!this.state.expanded) {
                var poweredByText = agent.server.name + " v" + agent.server.version;

                return (<div style={theme.snapBugBlock} onClick={this.onToggleBuildInfo} title="Click for detail..." >
                        <img src="/images/encapsule-holism.svg" style={{ width: '32px', height: '32px'}} /><br />
                        <span>{poweredByText}</span>
                        </div>);
            } else {

                const loggedIn = (session.data.username === 'anonymous')?(<strong>Logged Out:</strong>):(<strong>Logged In As:</strong>);

                var title = "Click to close detail...";

                return (<span>
                        <div style={theme.snapBugBlock} onClick={this.onToggleBuildInfo} title={title} >
                        <img src="/images/encapsule-holism.svg" style={{ width: '72px', height: '72px'}} /><br />

                        <p>Application: {agent.app.name} v{agent.app.version}</p>
                        <p>
                        Application runtime: {agent.integrations.name} v{agent.integrations.version}<br/>
                        Application server: {agent.server.name} v{agent.server.version}<br/>
                        Data processing: {agent.platform.data.name} v{agent.platform.data.version} {agent.platform.data.codename}<br/>
                        Document processing: {agent.platform.document.name} v{agent.platform.document.version}
                        </p>
                        <p>
                        Server instance: {agent.instance.id}<br/>
                        Server started: {agent.instance.ts}
                        </p>
                        <p>
                        {loggedIn} {session.data.firstName} {session.data.lastName} ({session.data.username}) / {session.data.email}<br/>
                        SessionID: {session.identity.sessionID?session.identity.sessionID:"anonymous-nonpersistent"}
                        </p>
                        </div>
                        <div style={{ padding: '1em' }}>
                        <div style={theme.snapBugBlock}>
                        <h2>Facebook React Component Properties (this.props)</h2></div>
                        <pre>{JSON.stringify(this.props,undefined,2)}</pre>
                        </div>

                        </span>
                       );
            }
        } catch (exception_) {
            return (<div>Fatal exception in {this.className}: {exception_.toString()}</div>);
        }
    }
});

module.exports = SnapBug;

