#!/usr/bin/env node

"use strict";

////
// INSPECT THE TARGET APPLICATION GIT REPOSITORY

////
// LOAD AND PARSE THE TARGET APPLICATION'S PACKAGE.JSON

////
// LOAD AND PARSE THE HOLISTIC PACKAGE'S BUILD MANIFEST

////
// GENERATE THE APPLICATION'S UPDATED PACKAGE.JSON

////
// OVERWRITE THE TARGET APPLICATION'S PACKAGE.JSON

////
// REMOVE ANY PREVIOUSLY-REGISTERED HOLISTIC RUNTIME

////
// UPDATE THE HOLISTIC RUNTIME (I.E. COPY THE RUNTIME PACKAGES)

////
// INSTALL THE UPDATED HOLISTIC RUNTIME (I.E. UPDATE yarn.lock)

////
// SYNTHESIZSE THE TARGET APPLICATION MAKEFILE

////
// SYNTHESIZE DOCUMENTATION & OTHER PERSISTENT ASSETS

////
// COMPLETE HOLISTIC APPLICATION UDPATE


